format = """
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$status\
$shell
[└─](#d78700)$character
"""

[character]
success_symbol = "[❯](bold #005faf)"

[directory]
style = "bold #005faf"
repo_root_style = "bold #005faf"
repo_root_format = "[+](bold green) [$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "bold green"

[git_status]
style = "#d78700"

[git_metrics]
disabled = true
